resources:
  - name: connect
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2
  - name: connect2
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2
  - name: resource_pipelines123
    type: GitRepo
    configuration:
      gitProvider: git_v
      path: vishnurao12/pipelines
      files: 
        include: ^README.md$
      branches:
        include: ^master$

pipelines:
  - name: testing_1213m
    steps:
      - name: first
        type: Bash
        configuration:
          inputResources: 
           - name: resource_pipelines123
             trigger: false
           - name: connect
             trigger: false
          integrations:
           - name: git_v
        execution:
          onExecute:
            - echo "hello"
          onSuccess:
            - echo "hello"

      - name: second
        type: Bash
        configuration:
          inputResources: 
           - name: resource_pipelines123
             trigger: false
           - name: connect
             trigger: false
          integrations:
           - name: git_v
        execution:
          onExecute:
            - echo "hello"
          onSuccess:
            - echo "hello"

      - name: myStepa1
        type: Bash
        configuration:
          inputResources: 
           - name: resource_pipelines123
             trigger: false
          integrations:
           - name: git_v
          inputSteps: 
           - name: first
           - name: second
          affinityGroup: "group1" 
        execution:
          onExecute:
            - echo "hello"
            - sleep 13m
          onSuccess:
            - echo "hello"

      - name: myStepa2
        type: Bash
        configuration:
          inputResources: 
           - name: resource_pipelines123
             trigger: false
          integrations:
           - name: git_v
          inputSteps: 
           - name: myStepa1
          affinityGroup: "group1"
          priority: 20 # optional
        execution:
          onExecute:
            - echo "hello"
            - sleep 20m
          onSuccess:
            - echo "hello"

      - name: myStepa3
        type: Bash
        configuration:
          inputResources: 
           - name: resource_pipelines123
             trigger: false
          integrations:
           - name: git_v
          inputSteps: 
           - name: myStepa1
          affinityGroup: "group1"
          priority: 30
        execution:
          onExecute:
            - echo "hello"
            - sleep 20m
          onSuccess:
            - echo "hello"

      - name: myStepa4
        type: Bash
        configuration:
          inputResources: 
           - name: resource_pipelines123
             trigger: false
          integrations:
           - name: git_v
          inputSteps: 
           - name: myStepa1
          affinityGroup: "group1" 
        execution:
          onExecute:
            - echo "hello"
            - sleep 13m
          onSuccess:
            - echo "hello"

      - name: myStepa5
        type: Bash
        configuration:
          inputResources: 
           - name: resource_pipelines123
             trigger: false
          integrations:
           - name: git_v
          inputSteps: 
           - name: myStepa4
          affinityGroup: "group1" 
        execution:
          onExecute:
            - echo "hello"
            - sleep 12m
          onSuccess:
            - echo "hello"

      - name: myStepa6
        type: Bash
        configuration:
          inputResources: 
           - name: resource_pipelines123
             trigger: false
          integrations:
           - name: git_v
          inputSteps: 
           - name: myStepa5
          affinityGroup: "group1" 
        execution:
          onExecute:
            - echo "hello"
            - sleep 12m
          onSuccess:
            - echo "hello"

      - name: myStepa7
        type: Bash
        configuration:
          inputResources: 
           - name: resource_pipelines123
             trigger: false
          integrations:
           - name: git_v
          inputSteps: 
           - name: myStepa6
          affinityGroup: "group1" 
        execution:
          onExecute:
            - echo "hello"
            - sleep 12m
          onSuccess:
            - echo "hello"


      - name: myStepb1
        type: Bash
        configuration:
          inputResources: 
            - name: resource_pipelines123
              trigger: false
          integrations:
            - name: git_v
          inputSteps: 
            - name: first
            - name: second 
          affinityGroup: "group1a"
        execution:
          onExecute:
            - echo "hello"
            - sleep 13m 

      - name: myStepb2
        type: Bash
        configuration:
          inputResources: 
            - name: resource_pipelines123
              trigger: false
          integrations:
            - name: git_v
          inputSteps: 
            - name: first
            - name: second 
          affinityGroup: "group1a"
        execution:
          onExecute:
            - echo "hello"
            - sleep 12m 

      - name: myStepb3
        type: Bash
        configuration:
          inputResources: 
            - name: resource_pipelines123
              trigger: false
          integrations:
            - name: git_v
          inputSteps: 
            - name: first
            - name: second 
          affinityGroup: "group1a"
        execution:
          onExecute:
            - echo "hello"
            - sleep 26m

      - name: myStepb4
        type: Bash
        configuration:
          inputResources: 
            - name: resource_pipelines123
              trigger: false
          integrations:
            - name: git_v
          inputSteps: 
            - name: first
            - name: second 
          affinityGroup: "group1a"
        execution:
          onExecute:
            - echo "hello"
            - sleep 18m 

      - name: myStepb5
        type: Bash
        configuration:
          inputResources: 
            - name: resource_pipelines123
              trigger: false
          integrations:
            - name: git_v
          inputSteps: 
            - name: myStepb1
          affinityGroup: "group1a"
        execution:
          onExecute:
            - echo "hello"
            - sleep 13m 

      - name: myStepb6
        type: Bash
        configuration:
          inputResources: 
            - name: resource_pipelines123
              trigger: false
          integrations:
            - name: git_v
          inputSteps: 
            - name: myStepb5
          affinityGroup: "group1a"
        execution:
          onExecute:
            - echo "hello"
            - sleep 30m 

      - name: myStepb7
        type: Bash
        configuration:
          inputResources: 
            - name: resource_pipelines123
              trigger: false
          integrations:
            - name: git_v
          inputSteps: 
            - name: myStepb6
          affinityGroup: "group1a"
        execution:
          onExecute:
            - echo "hello"
            - sleep 10m 

      - name: myStepb8
        type: Bash
        configuration:
          inputResources: 
            - name: resource_pipelines123
              trigger: false
          integrations:
            - name: git_v
          inputSteps: 
            - name: myStepb7
          affinityGroup: "group1a"
        execution:
          onExecute:
            - echo "hello"
            - sleep 20m 

      - name: myStepc1
        type: Bash
        configuration:
          inputResources: 
            - name: resource_pipelines123
              trigger: false
          integrations:
            - name: git_v
          inputSteps: 
            - name: myStepb2
          affinityGroup: "group2"
          outputResources:
            - name: connect2
        execution:
          onExecute:
            - echo "hello"
            - sleep 10m
          onSuccess:
            - write_output connect2 "testKey=$run_id"

      - name: myStepc2
        type: Bash
        configuration:
          inputResources: 
            - name: resource_pipelines123
              trigger: false
          integrations:
            - name: git_v
          inputSteps: 
            - name: myStepb2
          affinityGroup: "group2"
          outputResources:
            - name: connect2
        execution:
          onExecute:
            - echo "hello"
            - sleep 7m
          onSuccess:
            - write_output connect2 "testKey=$run_id"

      - name: myStepc3
        type: Bash
        configuration:
          inputResources: 
            - name: connect2
              trigger: true
          integrations:
            - name: git_v
          affinityGroup: "group2"
        execution:
          onExecute:
            - echo "hello"
          onSuccess:
            - echo "hello"

##########################################################################
##########################################################################
  - name: pipelines_123
    configuration:
      nodePool: win_2019
    steps:
      - name: first
        type: PowerShell
        configuration:
          inputResources: 
           - name: resource_pipelines123
             trigger: false
           - name: connect
             trigger: false
          integrations:
           - name: git_v
        execution:
          onExecute:
            - echo "hello"
          onSuccess:
            - echo "hello"

      - name: second
        type: PowerShell
        configuration:
          inputResources: 
           - name: resource_pipelines123
             trigger: false
           - name: connect
             trigger: false
          integrations:
           - name: git_v
        execution:
          onExecute:
            - echo "hello"
          onSuccess:
            - echo "hello"

      - name: myStepa1
        type: PowerShell
        configuration:
          inputResources: 
           - name: resource_pipelines123
             trigger: false
          integrations:
           - name: git_v
          inputSteps: 
           - name: first
           - name: second
          affinityGroup: "group1" 
        execution:
          onExecute:
            - echo "hello"
            - Start-Sleep -s 780
          onSuccess:
            - echo "hello"

      - name: myStepa2
        type: PowerShell
        configuration:
          inputResources: 
           - name: resource_pipelines123
             trigger: false
          integrations:
           - name: git_v
          inputSteps: 
           - name: myStepa1
          affinityGroup: "group1"
          priority: 20 # optional
        execution:
          onExecute:
            - echo "hello"
            - Start-Sleep -s 1200
          onSuccess:
            - echo "hello"

      - name: myStepa3
        type: PowerShell
        configuration:
          inputResources: 
           - name: resource_pipelines123
             trigger: false
          integrations:
           - name: git_v
          inputSteps: 
           - name: myStepa1
          affinityGroup: "group1"
          priority: 30
        execution:
          onExecute:
            - echo "hello"
            - Start-Sleep -s 1200
          onSuccess:
            - echo "hello"

      - name: myStepa4
        type: PowerShell
        configuration:
          inputResources: 
           - name: resource_pipelines123
             trigger: false
          integrations:
           - name: git_v
          inputSteps: 
           - name: myStepa1
          affinityGroup: "group1" 
        execution:
          onExecute:
            - echo "hello"
            - Start-Sleep -s 780
          onSuccess:
            - echo "hello"

      - name: myStepa5
        type: PowerShell
        configuration:
          inputResources: 
           - name: resource_pipelines123
             trigger: false
          integrations:
           - name: git_v
          inputSteps: 
           - name: myStepa4
          affinityGroup: "group1" 
        execution:
          onExecute:
            - echo "hello"
            - Start-Sleep -s 720
          onSuccess:
            - echo "hello"

      - name: myStepa6
        type: PowerShell
        configuration:
          inputResources: 
           - name: resource_pipelines123
             trigger: false
          integrations:
           - name: git_v
          inputSteps: 
           - name: myStepa5
          affinityGroup: "group1" 
        execution:
          onExecute:
            - echo "hello"
            - Start-Sleep -s 12m
          onSuccess:
            - echo "hello"

      - name: myStepa7
        type: PowerShell
        configuration:
          inputResources: 
           - name: resource_pipelines123
             trigger: false
          integrations:
           - name: git_v
          inputSteps: 
           - name: myStepa6
          affinityGroup: "group1" 
        execution:
          onExecute:
            - echo "hello"
            - Start-Sleep -s 12m
          onSuccess:
            - echo "hello"


      - name: myStepb1
        type: PowerShell
        configuration:
          inputResources: 
            - name: resource_pipelines123
              trigger: false
          integrations:
            - name: git_v
          inputSteps: 
            - name: first
            - name: second 
          affinityGroup: "group1a"
        execution:
          onExecute:
            - echo "hello"
            - Start-Sleep -s 780 

      - name: myStepb2
        type: PowerShell
        configuration:
          inputResources: 
            - name: resource_pipelines123
              trigger: false
          integrations:
            - name: git_v
          inputSteps: 
            - name: first
            - name: second 
          affinityGroup: "group1a"
        execution:
          onExecute:
            - echo "hello"
            - Start-Sleep -s 720 

      - name: myStepb3
        type: PowerShell
        configuration:
          inputResources: 
            - name: resource_pipelines123
              trigger: false
          integrations:
            - name: git_v
          inputSteps: 
            - name: first
            - name: second 
          affinityGroup: "group1a"
        execution:
          onExecute:
            - echo "hello"
            - Start-Sleep -s 1560

      - name: myStepb4
        type: PowerShell
        configuration:
          inputResources: 
            - name: resource_pipelines123
              trigger: false
          integrations:
            - name: git_v
          inputSteps: 
            - name: first
            - name: second 
          affinityGroup: "group1a"
        execution:
          onExecute:
            - echo "hello"
            - Start-Sleep -s 1080 

      - name: myStepb5
        type: PowerShell
        configuration:
          inputResources: 
            - name: resource_pipelines123
              trigger: false
          integrations:
            - name: git_v
          inputSteps: 
            - name: myStepb1
          affinityGroup: "group1a"
        execution:
          onExecute:
            - echo "hello"
            - Start-Sleep -s 780 

      - name: myStepb6
        type: PowerShell
        configuration:
          inputResources: 
            - name: resource_pipelines123
              trigger: false
          integrations:
            - name: git_v
          inputSteps: 
            - name: myStepb5
          affinityGroup: "group1a"
        execution:
          onExecute:
            - echo "hello"
            - Start-Sleep -s 1800 

      - name: myStepb7
        type: PowerShell
        configuration:
          inputResources: 
            - name: resource_pipelines123
              trigger: false
          integrations:
            - name: git_v
          inputSteps: 
            - name: myStepb6
          affinityGroup: "group1a"
        execution:
          onExecute:
            - echo "hello"
            - Start-Sleep -s 600 

      - name: myStepb8
        type: PowerShell
        configuration:
          inputResources: 
            - name: resource_pipelines123
              trigger: false
          integrations:
            - name: git_v
          inputSteps: 
            - name: myStepb7
          affinityGroup: "group1a"
        execution:
          onExecute:
            - echo "hello"
            - Start-Sleep -s 1200 

      - name: myStepc1
        type: PowerShell
        configuration:
          inputResources: 
            - name: resource_pipelines123
              trigger: false
          integrations:
            - name: git_v
          inputSteps: 
            - name: myStepb2
          affinityGroup: "group2"
          outputResources:
            - name: connect2
        execution:
          onExecute:
            - echo "hello"
            - Start-Sleep -s 600
          onSuccess:
            - write_output connect2 "testKey=$run_id"

      - name: myStepc2
        type: PowerShell
        configuration:
          inputResources: 
            - name: resource_pipelines123
              trigger: false
          integrations:
            - name: git_v
          inputSteps: 
            - name: myStepb2
          affinityGroup: "group2"
          outputResources:
            - name: connect2
        execution:
          onExecute:
            - echo "hello"
            - Start-Sleep -s 420
          onSuccess:
            - write_output connect2 "testKey=$run_id"

      - name: myStepc3
        type: PowerShell
        configuration:
          inputResources: 
            - name: connect2
              trigger: true
          integrations:
            - name: git_v
          affinityGroup: "group2"
        execution:
          onExecute:
            - echo "hello"
          onSuccess:
            - echo "hello"
