resources:
  - name: connecting_resource
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2
      
  - name: ns_dockerbuild_gitRepo
    type: GitRepo
    configuration:
      path: Khazinawaz/sample-script
      gitProvider: nawaz_gh
      branches: 
        include: master
        
  - name: res_bundle
    type: ReleaseBundle
    configuration:
      sourceDistribution: distribution_v
      name: test_123
      version: v1.0.3
      
  - name: sig_bundle
    type: ReleaseBundle
    configuration:
      sourceDistribution: distribution_v
      name: test_123
      version: v1.0.3
      
  - name: ns_promotedInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: art_v
      buildName: master_test_promotedInfo
      buildNumber: 1

  - name: ns_buildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: art_v
      buildName: master_test_buildInfo
      buildNumber: 1514
 
 
  - name:       out_image
    type:      Image
    configuration:
      registry:            art_v
      sourceRepository:    nawaz-docker   # required if registry is Artifactory
      imageName:           nawazeplus.jfrogdev.org/nawaz-docker-local/node:1.2.3
      imageTag:            1.2.3


pipelines:
  - name: docker_push

    steps:
      - name: To_build_Docker_Image
        type: DockerBuild
        configuration:
          affinityGroup: "BasicTest"
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: nawazeplus.jfrogdev.org/nawaz-docker-local/node
          dockerImageTag: 1.2.3
          integrations:
            - name: art_v

          inputResources:
            - name: ns_dockerbuild_gitRepo 
            - name: connecting_resource


      - name: To_Push_Docker_Image
        type: DockerPush
        configuration:
          affinityGroup: "BasicTest"
          autoPublishBuildInfo: true 
          forceXrayScan:        false
          failOnScan:           false
          targetRepository: nawaz-docker-local #required
          integrations:
            - name: art_v 
          inputSteps:
            - name: To_build_Docker_Image
          outputResources:
            - name: ns_buildInfo
            - name: out_image
               

      - name: To_promote_build
        type: PromoteBuild
        configuration:
          targetRepository: test-generic-local
          integrations:
            - name: art_v
          inputResources:
            - name: ns_buildInfo
          outputResources:
            - name: ns_promotedInfo

      - name: docker_releaseBundle
        type: CreateReleaseBundle
        configuration:
          #inherits from bash
          releaseBundleName:        test_123
          releaseBundleVersion:     v1.0.3
          inputResources:
            - name: ns_promotedInfo
          outputResources:
            - name: res_bundle
          dryRun: false
