resources:
  - name: EXT_S_LX_AU_0001_fileSpec
    type: FileSpec
    configuration:
      sourceArtifactory: s_artifactory
      pattern: "example-repo-local/EXT_S_LX_AU_0001_fileSpec.txt"

  - name: EXT_S_LX_AU_0001_propertyBag
    type: propertyBag
    configuration:
      sourceArtifactory: s_artifactory
      pattern: "example-repo-local/EXT_S_LX_AU_0001_fileSpec.txt"

pipelines:
  - name: pipeline_EXT_S_LX_AU_0001
    steps:
      - name: EXT_S_LX_AU_0001_1
        type: Bash
        configuration:
          integrations:
            - name: s_artifactory
          outputResources:
            - name: EXT_S_LX_AU_0001_fileSpec
        execution:
          onExecute:
            - echo "${run_id}" > EXT_S_LX_AU_0001_fileSpec.txt
            - jfrog rt upload EXT_S_LX_AU_0001_fileSpec.txt example-repo-local
            
      - name: EXT_S_LX_AU_0001_2
        type: jfrog_dev/UploadArtifact
        configuration:
          targetPath: example-repo-local/EXT_S_LX_AU_0001_fileSpec.txt"
          integrations:
            - name: s_artifactory
          inputResources:
            - name: EXT_S_LX_AU_0001_fileSpec

  - name: pipeline_EXT_S_LX_AU_0003
    steps:          
      - name: EXT_S_LX_AU_0001_3
        type: jfrog_dev/LinuxVMDeploy
        configuration:
          environmentVariables:
            DEPLOY_TARGETS_OVERRIDE: "test"
          targetDirectory: example-repo-local/EXT_S_LX_AU_0001_fileSpec.txt"
          deployCommand: "echo hi"

