resources:
  - name: connecting_resource
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2
      
  - name: promoted_build_info_gradle
    type: BuildInfo
    configuration:
      sourceArtifactory: art_v
      buildName: promotoed-full-gradle-native
      buildNumber: 1

  - name: gradle_repo
    type: GitRepo
    configuration:
      gitProvider: git_v
      path: vishnurao12/project-examples

  - name: build_info_gradle
    type: BuildInfo
    configuration:
      sourceArtifactory: art_v
      buildName: full-gradle-native
      buildNumber: 1
pipelines:
  - name: Master_test_pipe

    steps:
      - name: gradle_build_step
        type: GradleBuild
        configuration:
#           environmentVariables: # optional
#             JFROG_CLI_BUILD_NAME: "PIPE-f2387-gradle-build"
#             JFROG_CLI_BUILD_NUMBER: 2387
          gradleCommand: clean artifactoryPublish -b build.gradle
          sourceLocation: gradle-examples/gradle-example-minimal
          forceXrayScan:        true
          configFileLocation: .
          configFileName: gradle-art-config
          inputResources:
            - name: gradle_repo
            - name: connecting_resource
          integrations:
            - name: art_v
#           runtime: 
#             type: image
#             image: 
#               auto:
#                 language: java
#                 versions:
#                   - "8"
        execution:
          onStart:
            - javac -version
            - gradle --version

      - name: publish_build_info_gradle
        type: PublishBuildInfo
        execution:
          onStart:
            - echo "hello"
        configuration:
          inputSteps:
            - name: gradle_build_step
          outputResources:
            - name: build_info_gradle

      - name: promote_build_info_gradle
        type: PromoteBuild
        configuration:
          targetRepository: test-generic-local
          copy: true
          integrations:
            - name: art_v
#           runtime: 
#             type: image
#             image: 
#               auto:
#                 language: node
#                 versions:
#                   - "8.17.0"
          inputResources:
            - name: build_info_gradle
          outputResources:
            - name: promoted_build_info_gradle
