resources:
  - name: connecting_resource_node_test
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2


pipelines:
  - name: node_test
    steps:
      - name: myStep112
        type: Bash
        configuration:
          outputResources: 
            - name: connecting_resource_node_test
#               trigger: false
          integrations:
            - name: git_v
            - name: art_v
        execution:
          onExecute:
            - write_output connecting_resource_node_test "test:value"

      - name: win_2019
        type: PowerShell
        configuration:
          nodePool: win_2019
          inputResources:
            - name: connecting_resource_node_test
          integrations:
            - name: git_v
            - name: art_v  
        execution:
          onExecute:
            - write-output "Hi"
            - docker images
            - jfrog --version

      - name: u16
        type: Bash
        configuration:
          nodePool: u16
          inputResources:
            - name: connecting_resource_node_test
          integrations:
            - name: git_v
            - name: art_v
        execution:
          onExecute:
            - printenv
            - jfrog --version

      - name: c7node
        type: Bash
        configuration:
          nodePool: centos7
          integrations:
            - name: git_v
            - name: art_v
          inputResources:
            - name: connecting_resource_node_test
        execution:
          onExecute:
            - printenv
            - jfrog --version
            
      - name: c8node
        type: Bash
        configuration:
          nodePool: centos8
          integrations:
            - name: git_v
            - name: art_v
          inputResources:
            - name: connecting_resource_node_test
        execution:
          onExecute:
            - printenv
            - jfrog --version
            
      - name: u18
        type: Bash
        configuration:
          nodePool: u18
          integrations:
            - name: git_v
            - name: art_v
          inputResources:
            - name: connecting_resource_node_test
        execution:
          onExecute:
            - printenv
            - jfrog --version
            
      - name: u20
        type: Bash
        configuration:
          nodePool: u20
          integrations:
            - name: git_v
            - name: art_v
          inputResources:
            - name: connecting_resource_node_test
        execution:
          onExecute:
            - printenv
            - jfrog --version
            
      - name: rhel
        type: Bash
        configuration:
          nodePool: rhel7
          integrations:
            - name: git_v
            - name: art_v
          inputResources:
            - name: connecting_resource_node_test
        execution:
          onExecute:
            - printenv
            - jfrog --version
            
      - name: rhel8
        type: Bash
        configuration:
          nodePool: rhel8
          integrations:
            - name: git_v
            - name: art_v
          inputResources:
            - name: connecting_resource_node_test
        execution:
          onExecute:
            - printenv
            - jfrog --version
