resources:
  - name: prop
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2


pipelines:
  - name: node_test
    steps:
      - name: myStep112
        type: Bash
        configuration:
          outputResources: 
            - name: prop
#               trigger: false
#           integrations:
#             - name: git_v
        execution:
          onExecute:
            - write_output prop "test:value"

      - name: u16
        type: Bash
        configuration:
#           nodePool: u16
          inputResources:
            - name: prop
        execution:
          onExecute:
            - printenv
