resources:
 - name: resource_pipelines1245
   type: GitRepo
   configuration:
     gitProvider: git_v1
     path: vishnurao12/pipelines
     files: 
       include: ^README.md$
     branches:
       include: ^{{gitBranch}}$
#      buildOn:
#        pullRequestCreate: true
#      cancelPendingRunsOn:
#        pullRequestUpdate: true

pipelines:
  - name: testing_123
    configuration:
      retentionPolicy:
        maxAgeDays: 1
        minRuns: 5
    steps:
      - name: myStep1
        type: Bash
        configuration:
#           retentionPolicy:
#             maxAgeDays: 2
#             minRuns: 1000
#           inputResources: 
#             - name: cron_5min
          integrations:
            - name: git_v1
        execution:
          onExecute:
            - touch sample.txt
            - echo test>sample.txt
            - add_cache_files sample.txt sample
            - add_run_variables sample:$run_id



      
