resources:
  - name: cron_min
    type: CronTrigger
    configuration:
      interval: "* * * * *"

pipelines:
  - name: kogerPipelineId10Steps7Runs4

    steps:
      - name: myStep1
        type: Bash
        configuration:
          integrations:
            - name: git_v
        execution:
          onExecute:
            - touch sample.txt

            
      - name: myStep2
        type: Bash
        configuration:

          inputSteps: 
            - name: myStep1
          integrations:
            - name: git_v
        execution:
          onExecute:
            - touch sample.txt

            
      - name: myStep3
        type: Bash
        configuration:

          inputSteps: 
            - name: myStep1
          integrations:
            - name: git_v
        execution:
          onExecute:
            - touch sample.txt

            
      - name: myStep4
        type: Bash
        configuration:

          inputSteps: 
            - name: myStep1
          integrations:
            - name: git_v
        execution:
          onExecute:
            - touch sample.txt
            
      - name: myStep5
        type: Bash
        configuration:

          inputSteps: 
            - name: myStep1
          integrations:
            - name: git_v
        execution:
          onExecute:
            - touch sample.txt

      - name: myStep6
        type: Bash
        configuration:

          inputSteps: 
            - name: myStep1
          integrations:
            - name: git_v
        execution:
          onExecute:
            - touch sample.txt
 
      - name: myStep7
        type: Bash
        configuration:

          inputSteps: 
            - name: myStep1
          integrations:
            - name: git_v
        execution:
          onExecute:
            - touch sample.txt

#-------------------------------------------------------------------------------------


  - name: kogerPipelineId11Steps1Runs1

    steps:
      - name: myStep1
        type: Bash
        configuration:
          integrations:
            - name: git_v
        execution:
          onExecute:
            - touch sample.txt

            
#-------------------------------------------------------------------------------------

  - name: kogerPipelineId12Steps1Runs12

    steps:
      - name: myStep1
        type: Bash
        configuration:
          integrations:
            - name: git_v
        execution:
          onExecute:
            - touch sample.txt

 #-------------------------------------------------------------------------------------
   
   - name: smartthingsPipelineId11Steps4Runs70

    steps:
      - name: myStep1
        type: Bash
        configuration:
          inputResources:
            - name: cron_min
          integrations:
            - name: git_v
        execution:
          onExecute:
            - touch sample.txt

            
      - name: myStep2
        type: Bash
        configuration:

          inputSteps: 
            - name: myStep1
          integrations:
            - name: git_v
        execution:
          onExecute:
            - touch sample.txt

            
      - name: myStep3
        type: Bash
        configuration:

          inputSteps: 
            - name: myStep1
          integrations:
            - name: git_v
        execution:
          onExecute:
            - touch sample.txt

            
      - name: myStep4
        type: Bash
        configuration:

          inputSteps: 
            - name: myStep1
          integrations:
            - name: git_v
        execution:
          onExecute:
            - touch sample.txt

 #-------------------------------------------------------------------------------------
 
- name: smartthingsPipelineId12Steps4Runs4

    steps:
      - name: myStep1
        type: Bash
        configuration:
          integrations:
            - name: git_v
        execution:
          onExecute:
            - touch sample.txt

            
      - name: myStep2
        type: Bash
        configuration:

          inputSteps: 
            - name: myStep1
          integrations:
            - name: git_v
        execution:
          onExecute:
            - touch sample.txt

            
      - name: myStep3
        type: Bash
        configuration:

          inputSteps: 
            - name: myStep1
          integrations:
            - name: git_v
        execution:
          onExecute:
            - touch sample.txt

            
      - name: myStep4
        type: Bash
        configuration:

          inputSteps: 
            - name: myStep1
          integrations:
            - name: git_v
        execution:
          onExecute:
            - touch sample.txt
