resources:
  - name: connecting_resource
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2
      
  - name: resource_pipelines1245
    type: GitRepo
    configuration:
      gitProvider: git_v
      path: vishnurao12/pipelines
      files: 
        include: ^README.md$
      branches:
        include: ^{{gitBranch}}$
      
  

pipelines:
  - name: pipelines_12
    configuration:
      environmentVariables:
        readOnly:
          pipeline_env_var:
            default: value1
            description: test
            allowCustom: true
            values:
              - value1
              - value2
          pipeline_env_var1:
            default: value1
            values:
              - value1
              - value2
    steps:
    - name: step_1
      type: Bash
      configuration:
        environmentVariables:
          test: test
          step_env_va1r:
            default: value1
            values:
              - value1
              - value2
          step_env_var:
            default: value1
            description: test
            allowCustom: true
            values:
              - value1
              - value2
        outputResources:
          - name: connecting_resource

      execution:
        onExecute:
          - echo "${step_name} running"   

    - name: step_2
      type: Bash
      configuration:
        inputResources:
          - name: connecting_resource
            trigger: false
      execution:
        onExecute:
          - echo "${step_name} running"   
