resources:
 - name: resource_pipelines1245
   type: GitRepo
   configuration:
     gitProvider: git_v1
     path: vishnurao12/pipelines
     files: 
       include: ^README.md$
     branches:
       include: ^{{gitBranch}}$
#      buildOn:
#        pullRequestCreate: true
#      cancelPendingRunsOn:
#        pullRequestUpdate: true

pipelines:
  - name: testing_123
    steps:
      - name: myStep112
        type: Bash
        configuration:
         environmentVariables:
           testCases: setup.js
          
         inputResources: 
           - name: resource_pipelines1245
         integrations:
           - name: git_v1
           - name: art_v1
        execution:
          onExecute:
            - docker images
            - printenv | grep "testCases"
            - echo $testCases
            - testcaseDup="[\"core/testHarness/$testCases\"]"
            - echo $testcaseDup
            - pushd $res_resource_pipelines1245_resourcePath
            - ls
            - echo "hi"
#             - cat doesnotexist.txt
#             - sleep 15m
          onSuccess:
            - pushd $res_resource_pipelines1245_resourcePath
            - ls



      
