resources:
  - name: repo_git
    type: GitRepo
    configuration:
      path: vishnurao12/pipelines
      gitProvider: git_v
      
      buildOn:
        commit: false
        pullRequestCreate: true
        pullRequestClose: true

pipelines:
  - name: test
    steps:
      - name: test
        type: Bash
        configuration:
          inputResources:
            - name: repo_git
              trigger: true
        execution:
          onExecute:
            - printenv


      
