resources:
 - name: testp123
   type: GitRepo
   configuration:
     gitProvider: git_v
     path: vishnurao12/pipelines

pipelines:
  - name: testP121
    steps:
      - name: testP1222
        type: PowerShell
        configuration:
          integrations:
            - name: art_v
          nodePool: win_2019-1
          inputResources: 
          - name: testp123
        execution:
          onExecute:
            - dotnet --version

